---
- name: Converge
  hosts: all
  become: no

  vars:
    vim_install_autoload_scripts:
      - filename: pathogen.vim
        url: https://tpo.pe/pathogen.vim
    vim_install_plugins:
      - name: vim-sensible
        repo: https://github.com/tpope/vim-sensible.git
      - name: ansible-vim
        repo: https://github.com/pearofducks/ansible-vim.git
    vim_install_vimrc: yes
    vim_local_vimrc_url: https://raw.githubusercontent.com/jrgoldfinemiddleton/dotfiles/master/.vimrc
    vim_local_vimrc_path: '~{{ ansible_user_id }}/.vimrc'

  pre_tasks:
    - name: Allow Ubuntu 14.04 to make HTTPS connections
      block:
        - name: Ensure software-properties-common is installed
          apt:
            name: software-properties-common
            install_recommends: no
            update_cache: yes
            cache_valid_time: 3600
            state: present

        - name: Ensure jonathonf/python-2.7 repo is in APT sources list
          apt_repository:
            repo: ppa:jonathonf/python-2.7

        - name: Ensure Python 2.7 is installed
          apt:
            name: python2.7
            install_recommends: no
            update_cache: yes
            cache_valid_time: 3600
            state: latest
          # ignore ansible-lint's APT 'latest' rule
          tags:
            - skip_ansible_lint
      become: yes
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version is version('14.04', '=')

  roles:
    - role: geerlingguy.git
    - role: jrgoldfinemiddleton.vim
